import mysql.connector

# Establecer conexión con la base de datos
cnx = mysql.connector.connect(user='usuario', password='contraseña',
                              host='localhost',
                              database='nombre_de_la_base_de_datos')
cursor = cnx.cursor()

# Definir los registros que se van a insertar
registros = [
  ("Valor1", "Valor2", "Valor3"),
  ("Valor4", "Valor5", "Valor6"),
  ("Valor7", "Valor8", "Valor9")
]

# Definir la consulta SQL para insertar registros
consulta = "INSERT INTO tabla (campo1, campo2, campo3) VALUES (%s, %s, %s)"

# Insertar los registros utilizando la consulta preparada
cursor.executemany(consulta, registros)

# Confirmar los cambios y cerrar la conexión
cnx.commit()
cursor.close()
cnx.close()
